{{- if .Values.nextcloud.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  {{- if .Values.nextcloud.storageClass }}
  storageClassName: {{ .Values.nextcloud.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.nextcloud.storage }}
{{- end }}

{{- if .Values.prometheus.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.prometheus.storageClass }}
  storageClassName: {{ .Values.prometheus.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage }}
{{- end }}

{{- if .Values.grafana.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.grafana.storageClass }}
  storageClassName: {{ .Values.grafana.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.storage }}
{{- end }}
