apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgresql.password | quote }}
  nextcloud-admin-password: {{ .Values.nextcloud.adminPassword | quote }}
  grafana-admin-password: {{ .Values.grafana.adminPassword | quote }}
